use anyhow::Result;
use directories;
use std::path::PathBuf;

const XDG_GIT_CONFIG: &str = "git/config";
const XDG_GIT_CONFIG_D: &str = "git/config.d";

pub fn xdg_config_home() -> PathBuf {
    std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            let mut home = directories::BaseDirs::new()
                .expect("Cannot determine home directory")
                .config_dir()
                .to_path_buf();
            home
        })
}

pub fn xdg_git_dir() -> PathBuf {
    xdg_config_home().join("git")
}

pub fn xdg_git_config() -> PathBuf {
    xdg_git_dir().join("config")
}

pub fn xdg_git_config_d() -> PathBuf {
    xdg_git_dir().join("config.d")
}

pub fn add_git_alias(name: &str, command: &str) -> Result<()> {
    let mut cmd = std::process::Command::new("git");
    cmd.args(["config", "--global", &format!("alias.{}", name), command]);

    let output = cmd
        .output()
        .context("Failed to execute git config command")?;

    if !output.status.success() {
        anyhow::bail!(
            "git config failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    Ok(())
}

pub fn ensure_git_config_d_include() -> Result<()> {
    let config_file = xdg_git_config();
    let config_d = xdg_git_config_d();

    std::fs::create_dir_all(&config_d)?;

    if !config_file.exists() {
        std::fs::write(&config_file, "# Generated by git-config-d\n")?;
    }

    let config_content = std::fs::read_to_string(&config_file)
        .with_context(|| format!("Failed to read file: {}", config_file.display()))?;

    let include_pattern = format!("path = {}/\\*.conf", config_d.display());

    if config_content.contains(&include_pattern) {
        return Ok(());
    }

    let mut file = std::fs::OpenOptions::new()
        .append(true)
        .open(&config_file)
        .with_context(|| format!("Failed to open file for writing: {}", config_file.display()))?;

    use std::io::Write;
    writeln!(file)?;
    writeln!(file, "[include]")?;
    writeln!(file, "    path = {}/*.conf", config_d.display())?;

    Ok(())
}

pub fn ensure_git_alias(name: &str, command: &str) -> Result<()> {
    ensure_git_config_d_include()?;

    let config_d = xdg_git_config_d();
    let alias_file = config_d.join("aliases.conf");

    std::fs::create_dir_all(&config_d)
        .with_context(|| format!("Failed to create directory: {}", config_d.display()))?;

    let content = if alias_file.exists() {
        std::fs::read_to_string(&alias_file)
            .with_context(|| format!("Failed to read file: {}", alias_file.display()))?
    } else {
        String::new()
    };

    let alias_line = format!("[alias]\n    {} = {}", name, command);

    if content.contains(&format!("{} = {}", name, command)) {
        return Ok(());
    }

    let mut file = std::fs::OpenOptions::new()
        .append(true)
        .create(true)
        .open(&alias_file)
        .with_context(|| format!("Failed to open file for writing: {}", alias_file.display()))?;

    use std::io::Write;

    if !content.ends_with('\n') && !content.is_empty() {
        writeln!(file)?;
    }

    if !content.contains("[alias]") {
        writeln!(file, "[alias]")?;
    }

    writeln!(file, "    {} = {}", name, command)?;

    Ok(())
}
