use anyhow::{Context, Result};
use std::io::Write;

use crate::paths;

pub fn add_git_alias(name: &str, command: &str) -> Result<()> {
    let mut cmd = std::process::Command::new("git");
    cmd.args(["config", "--global", &format!("alias.{}", name), command]);

    let output = cmd
        .output()
        .context("Failed to execute git config command")?;

    if !output.status.success() {
        anyhow::bail!(
            "git config failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    Ok(())
}

pub fn ensure_git_config_d_include() -> Result<()> {
    let config_file = paths::xdg_git_config();
    let config_d = paths::xdg_git_config_d();

    std::fs::create_dir_all(&config_d)?;

    if !config_file.exists() {
        std::fs::write(&config_file, "# Generated by git-config-d\n")?;
    }

    let config_content = std::fs::read_to_string(&config_file)?;

    let include_pattern = format!("path = {}/*.conf", config_d.display());

    if config_content.contains(&include_pattern) {
        return Ok(());
    }

    let mut file = std::fs::OpenOptions::new()
        .append(true)
        .open(&config_file)?;

    writeln!(file)?;
    writeln!(file, "[include]")?;
    writeln!(file, "    path = {}/*.conf", config_d.display())?;

    Ok(())
}

pub fn ensure_git_alias(name: &str, command: &str) -> Result<()> {
    ensure_git_config_d_include()?;

    let config_d = paths::xdg_git_config_d();
    let alias_file = config_d.join("aliases.conf");

    std::fs::create_dir_all(&config_d)?;

    let content = if alias_file.exists() {
        std::fs::read_to_string(&alias_file)?
    } else {
        String::new()
    };

    if content.contains(&format!("{} = {}", name, command)) {
        return Ok(());
    }

    let mut file = std::fs::OpenOptions::new()
        .append(true)
        .create(true)
        .open(&alias_file)?;

    if !content.ends_with('\n') && !content.is_empty() {
        writeln!(file)?;
    }

    if !content.contains("[alias]") {
        writeln!(file, "[alias]")?;
    }

    writeln!(file, "    {} = {}", name, command)?;

    Ok(())
}
